"use client";

import { FormEvent, useState } from "react";
import { IconCheck, IconLoader2 } from "@tabler/icons-react";

export function DesignPartnerForm() {
  const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [done, setDone] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(null); const form = new FormData(event.currentTarget); const response = await fetch("/api/design-partner/apply", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); const result = await response.json(); setLoading(false); if (!response.ok) return setError(result.error ?? "Application failed"); setDone(true); }
  if (done) return <div className="partner-success"><IconCheck size={30} /><h2>Application received</h2><p>If your workflow matches Shadow Mode, the next step is a 30-minute session using your real OpenAPI contract.</p></div>;
  return <form className="partner-form" onSubmit={submit}><div className="form-grid"><label>Company name<input name="companyName" required minLength={2} /></label><label>Your name<input name="contactName" required minLength={2} /></label><label>Work email<input name="workEmail" type="email" required /></label><label>Role<input name="roleTitle" required placeholder="CTO, VP Engineering, API lead" /></label><label>Company URL<input name="companyUrl" type="url" required placeholder="https://company.com" /></label><label>OpenAPI URL <span>Optional</span><input name="apiSpecUrl" type="url" placeholder="https://api.company.com/openapi.json" /></label></div><label>Current agent-access demand<select name="agentDemand" required defaultValue=""><option value="" disabled>Select one</option><option value="customer_requests">Customers have requested MCP or agent access</option><option value="active_build">We are actively building agent access</option><option value="exploring">We are exploring it this quarter</option><option value="none">No active demand yet</option></select></label><label>One workflow an external agent should perform<textarea name="targetWorkflow" required minLength={20} placeholder="Example: A customer’s coding agent should list deployment failures and open a rollback request without receiving our staging API key." /></label><label>Desired timeline<select name="timeline" required defaultValue=""><option value="" disabled>Select one</option><option value="this_week">This week</option><option value="this_month">This month</option><option value="this_quarter">This quarter</option><option value="researching">Researching only</option></select></label><input type="hidden" name="website" value="" />{error && <p className="form-error">{error}</p>}<button className="button primary large" type="submit" disabled={loading}>{loading && <IconLoader2 className="spin" size={17} />}Apply with a real workflow</button><small>We do not require production credentials. The first connection is staging and read-only.</small></form>;
}
